### ISSUE TITLE
Error: Redis connection to 127.0.0.1:6379

### ISSUE THREAD

**Issue by gitbit12665** [misi/mm#5]
I have created the container according to instructions.
Every time I start up the docker log shows this error:

```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at RedisClient.on_error (/opt/multiparty-meeting/server/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/opt/multiparty-meeting/server/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Container starting up...
- process.env.DEBUG: undefined
- config.mediasoup.logLevel: undefined
- config.mediasoup.logTags: undefined
events.js:174
      throw er; // Unhandled 'error' event
      ^
```

**Comment by misi** [comment]
Install and start a redis on your instance...
Or use docker-compose..
docker-compose up
